---
################################################################
################ Step 1: Set up the app servers ################
################################################################
- name: Configure App Servers
  hosts: app_servers_*
  roles:
    - app_server

################################################################
############### Step 2: Set up the load balancer ###############
################################################################

- name: Configure Load Balancer Servers
  hosts: lb_servers
  roles:
    - lb_server
